### PR TITLE
1.3.0

### PR DESCRIPTION
**Pull request by ehmicky**
Release `1.3.0`

### CODE REVIEW

**Review by mraerino — APPROVED** [review]

**Comment by shortdiv** [comment]
Should we update the readme #62 before bumping the version?

**Comment by mraerino** [comment]
what's the conflict? i think mickael already published when he makes these

**Comment by shortdiv** [comment]
Good point, there isn't a conflict just wanted to see if we can weasel in updates to the readme in the new version

**Review by shortdiv — APPROVED** [review]

**Comment by ehmicky** [comment]
I run `npm publish` only after merging this type of PRs. Please let me know if this works!

**Pull request merged**
