### PR TITLE
chore: add release PR flow

### PR DESCRIPTION
**Pull request by erezrokah**
This adds an action to create release PRs based on commit messages

### CODE REVIEW

**Review by mraerino — APPROVED** [review]
this is an awesome flow!

why are we not using the flow that also publishes to npm?
https://github.com/google-github-actions/release-please-action#automating-publication-to-npm

**Comment by erezrokah** [comment]
> why are we not using the flow that also publishes to npm?
> https://github.com/google-github-actions/release-please-action#automating-publication-to-npm

We need to disable 2FA for that (or use an automation token from a bot).
We can add the automated publish flow once we finish discussing https://github.com/netlify/engineering/issues/177.

**Comment by mraerino** [comment]
cool. +1 for using an automation token from me

**Comment by erezrokah** [comment]
FYI, we have a wrong release and tag I'm going to remove (already pushed the correct tags):
image
image

**Pull request merged**
