### PR TITLE
fix: Add terser

### PR DESCRIPTION
**Pull request by shortdiv**
**Which problem is this pull request solving?**
Addresses the discussion in #73 to minify es bundles. 

**List other issues or pull requests related to this problem**
#76 

**Checklist**
- [x] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Review by ehmicky — APPROVED** [review]
Amazing!
:tada:

**Comment by ehmicky** [comment]
I have tried locally.

The `integration-test` big fixture goes from `556727` to `122,656` bytes (78% reduction).

The `config-dir` very small fixture goes from `245` to `122` bytes (50% reduction).

Before this PR:

```js
(function(){'use strict';function onRequest() {}var funcc3499c2729730a7f807efb8676a92dcb6f8a3f8f=/*#__PURE__*/Object.freeze({__proto__:null,onRequest: onRequest});netlifyRegistry.set("example", funcc3499c2729730a7f807efb8676a92dcb6f8a3f8f);}());
```

After this PR:

```js
!function(){"use strict";var e=Object.freeze({__proto__:null,onRequest:function(){}});netlifyRegistry.set("example",e)}();
```

**Comment by ehmicky** [comment]
Note: this reduces the `func{randomID}` to single letter variables. I have been wondering whether this would reverse the benefits of #66 (consistent bundle filenames). 

However, this is not the case. The minified bundle content is the same when the source code does not change, and is different when the source code changes. Since the bundle filename is a hash of the bundle content, this should work.

**Review by mraerino — APPROVED** [review]
great!

**Pull request merged**
