### PR TITLE
security: use node-polyfills instead of node-builtins

### LINKED ISSUE #97: Security: npm audit reports security issues for rollup-plugin-node-builtins
**Describe the bug**

Netlify CLI uses this plugin as a dependency through Netlify Build.
Running `npm audit` on the CLI repo reports the following:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ semver                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.3.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @netlify/build                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @netlify/build > @netlify/plugin-edge-handlers >             │
│               │ rollup-plugin-node-builtins > browserify-fs > levelup >      │
│               │ semver                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/31                              │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Memory Exposure                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bl                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.9.5 <1.0.0 || >=1.0.1                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @netlify/build                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @netlify/build > @netlify/plugin-edge-handlers >             │
│               │ rollup-plugin-node-builtins > browserify-fs > levelup > bl   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/596                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Remote Memory Exposure                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bl                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.3 <2.0.0 || >=2.2.1 <3.0.0 || >=3.0.1 <4.0.0 ||        │
│               │ >=4.0.3                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @netlify/build                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @netlify/build > @netlify/plugin-edge-handlers >             │
│               │ rollup-plugin-node-builtins > browserify-fs > levelup > bl   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1555      
```

**Reproduction**

- `git clone git@github.com:netlify/cli.git`
- `cd cli`
- `npm ci`
- `npm audit`

**Pull requests**

Not sure how to fix this as the library is no longer maintained. Inlining it will probably remove the errors but won't fix the security issues (unless we fix those ourselves). We can also fork the repo, fix the issues and publish it as a new package.

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes https://github.com/netlify/netlify-plugin-edge-handlers/issues/97 based on https://github.com/netlify/netlify-plugin-edge-handlers/issues/97#issuecomment-734197509

Is there a suggestion on how to test this change?

### CODE REVIEW

**Comment by mraerino** [comment]
https://github.com/netlify/edge-handler-test-site uses it in a dependency, so if you can run the build of that site using this branch we should be good as a start

**Comment by erezrokah** [comment]
Added a test for this and also deploy an edge handler that uses `process` in:
https://app.netlify.com/sites/edge-handler-test-site-main/edge-handlers/version

I don't see any logs though. I've looked in other handles and sites and I don't see logs there either.

**Comment by mraerino** [comment]
the site was missing the assignment of a subdomain of `*.edge-handlers.dev`. i added it and am able to see logs here: https://app.netlify.com/sites/edge-handler-test-site-main/edge-handlers/logging

**Review by mraerino — DISMISSED** [review]

**Comment by mraerino** [comment]
the html processing which needs node builtins also works: https://app.netlify.com/sites/edge-handler-test-site-main/edge-handlers/location-insert

**Review by mraerino — DISMISSED** [review]

**Comment by erezrokah** [comment]
@mraerino I updated my site to install the plugin from this branch (before it was installing the plugin from `master`). Logs are coming up empty:
https://app.netlify.com/sites/edge-handler-test-site-main/deploys/5ff3540e6b5f73000749179e
https://app.netlify.com/sites/edge-handler-test-site-main/edge-handlers/logging

What am I missing here?

**Comment by mraerino** [comment]
How did you invoke the edge handler? You should use `test-site-erez.edge-handlers.dev` as the domain so it goes to the beta nodes

**Comment by erezrokah** [comment]
> How did you invoke the edge handler? You should use `test-site-erez.edge-handlers.dev` as the domain so it goes to the beta nodes

My bad, should have read the docs first. I didn't add a redirect to invoke my edge handler, nor did I visit the correct path for the other ones.

Seems to be working correctly with the new branch

**Review by mraerino — APPROVED** [review]

**Pull request merged**
