### PR TITLE
1.8.0

### PR DESCRIPTION
**Pull request by ehmicky**
Release `1.8.0`

### CODE REVIEW

**Comment by mraerino** [comment]
i have some doubts around releasing this. i want to get some fixes in around the node compat stuff. can we hold up on the release for now?

see https://github.com/netlify/netlify-plugin-edge-handlers/pull/88#issuecomment-703713149

**Comment by ehmicky** [comment]
:+1:

**Comment by mraerino** [comment]
if we land this PR, we can continue releasing: https://github.com/netlify/netlify-plugin-edge-handlers/pull/93

**Review by mraerino — COMMENTED** [review]
good to go now, if you rebase onto master

**Comment by ehmicky** [comment]
Rebased :+1:

**Review by mraerino — APPROVED** [review]
awesome!

**Pull request merged**
