### PR TITLE
Allow setting custom source dir via input

### PR DESCRIPTION
**Pull request by mraerino**
🎉 Thanks for sending this pull request! 🎉

Please make sure the title is clear and descriptive.

If you are fixing a typo or documentation, please skip these instructions.

Otherwise please fill in the sections below.

**Which problem is this pull request solving?**

Example: I'm always frustrated when [...]

**List other issues or pull requests related to this problem**

Example: This fixes #5012

**Describe the solution you've chosen**

Example: I've fixed this by [...]

**Describe alternatives you've considered**

Example: Another solution would be [...]

**Checklist**

Please add a `x` inside each checkbox:

- [ ] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Comment by ehmicky** [comment]
What would be the benefits of using a plugin inputs for users instead of using the `build.edge_handlers` configuration property?

**Comment by mraerino** [comment]
if i want to test a pre-release of this plugin without updating the buildbot image, i need to be able to run this plugin explicitly from the package in my repo.

- I can't use the default name `edge-handlers` for the dir name, because that means the core plugin would run after mine
- if I set `build.edge_handlers` the official core plugin would run, too

this is more of a developer productivity thing than anything publicly facing

**Comment by ehmicky** [comment]
> if I set build.edge_handlers the official core plugin would run, too

It does not. I have added the following logic because I ran into the same problem you are facing:

https://github.com/netlify/build/blob/725f36c60d1ee5a43b2cfe2fb8c1c923979d327b/packages/build/src/plugins/options.js#L79-L90

If you set `build.edge_handlers`, the official core plugin should not run.

**Comment by mraerino** [comment]
oh, awesome. didn't know.
That's very handy!

**Pull request closed without merging**
